= Programming II Project

Dominique Brodbeck & Rahel Lüthy · Fachhochschule Nordwestschweiz · 2016

== Requirements

Your task is to implement a JavaFX application which allows to visually analyze measurement data.

[[basic-requirements]]
=== Basic Requirements

==== Input Data Loading
Data for two variables is loaded from an input file.
The application supports two different input data formats (see section <<data-formats>> for details).
The first format corresponds to a traditional *tab-delimited* format (one column per variable, one row per measurement, values separated by tab character).
The second format is *line-oriented* (one line per variable, values separated by configurable delimiter).

The name of the loaded data file is visible in the application window.

==== Visualization
Data values are visualized using the following charts:

* A *scatter plot* shows how two variables are related.
* For each variable: A *histogram plot* visualizes how measurement values are distributed.

All plots adjust in size if the main application window is resized.

===== Scatter Plot
The user interface offers a configuration option to connect all scatter plot points with a line (according to the sequence of measurements in the input file).
This functionality can be useful for time series data, where one of the variables is representing a timestamp.

It is possible to smoothly control the size of scatter plot points.

===== Histogram
Histograms are labelled according to the displayed variable.
The number and width of histogram bins is determined automatically, e.g. using a square-root choice (see https://en.wikipedia.org/wiki/Histogram#Number_of_bins_and_width[Wikipedia]).

[[additional-requirements]]
=== Additional Requirements

==== Code Quality
For the sake of structure and modularity, all code is organized into Java packages.
Code follows a generally accepted coding style (see Moodle "Coding Conventions" presentation).

==== Exception Handling
In case of exceptions (particularly during file import), the application does not crash, but displays a useful error message.

==== Polymorphism
Loading of different data formats is abstracted behind a Java `interface`.
This guarantees extensibility with respect to future data formats.

==== Scatter Plot Labelling
Both scatter plot axes are labelled according to the displayed variables.

==== Scatter Plot Coloring
A chooser allows to freely pick an arbitrary point color (one color for all scatter plot points).

==== Multiple Variables
Both data formats are flexible enough to not only support two, but arbitrary many variables.
The application can load & display multiple variables.
If multiple variables are loaded, users can select which variables to use for the scatter plot x- and y-axis.
Both histograms adapt accordingly.

==== Bubble Plot
To analyze relationships between three variables, it is possible to select a third variable, which is used to scale scatter plot point sizes.
This effectively turns the scatter plot into a bubble plot.

[[data-formats]]
=== Data Formats

==== Tab-Delimited Format
This is a very common, simple, text-based file format.
It can e.g. be read and written by Excel ("Tab Delimited Text (.txt)").

Example (2 variables, 5 measurements):
[source]
----
Variable 1\tVariable 2
262.1\t400.0
319.0\t388.2
364.2\t362.0
400.0\t320.2
418.0\t262.0
----

The first line contains one name for each variable.
Each further line contains one measurement (one value for each variable).
Measurement values are delimited by a tab character ("\t" in Java).

==== Line-Oriented Format
This is a non-standard, text-based file format, like it could e.g. be used by an instrument vendor to export measurement data.
The format is line-oriented.

Example (2 variables, 5 measurements):
[source]
----
2
Variable 1
Variable 2
;
2620.0;3190.2;3640.0;4000.0;4180.0
4000.1;3880.0;3620.1;3200.0;2620.0
----

Lines are interpreted as follows:

* Line `1`: Number of Variables `n`
* Lines `2` to `n+1`: Variable names
* Line `n+2`: Delimiter (i.e. character to be used to separate measurement values)
* Lines `n+3` to `2*(n+1)`: one line of measurement values per variable, separated by previously specified delimiter

== Implementation
=== Technology & Concepts
The project must be implemented in Java 8, using concepts learned throughout the "Programming II" course.
The graphical user interface (GUI) must be implemented in JavaFX.
The GUI must be implemented programmatically, i.e. without using visual layout tools like _Scene Builder_.
No additional libraries shall be used.

=== Organisation
The project must be implemented in student groups of two.
Please notify rahel.luethy@fhnw.ch of your group composition by May 4, 2016.
The final application must be submitted via Moodle (ZIP/RAR/TAR archive containing complete, runnable source code).

IMPORTANT: Project submission deadline: Sunday, June 5, 2016 24:00 CEST

== Grading
The final project grade accounts for 50% of the module grade (the other 50% are determined by the written exam).
Applications which are not executable or do not fulfill all basic requirements are marked with a *grade below 4*.
Completion of all <<basic-requirements,basic requirements>> correspond to *grade 4*.
Completion of <<additional-requirements, additional requirements>> leads to a *higher grade* (credit depending on scope and complexity of requirement).
A project is marked with *grade 6* if all basic requirements and all additional requirements are fulfilled completely.

== The Fine Print
Please work independently, in groups of two.
Plagiarism is punished with grade 1.
Thank you for your understanding & your effort – good luck!
